version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/urlshortener?sslmode=disable
      - SERVER_PORT=8080
      - LOG_LEVEL=development
      - RATE_LIMIT=100
    depends_on:
      - db

  db:
    image: postgres:13
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    volumes:
      # first my local dir, second default for everyone
      #- D:/Base/Downloads/example_db:/var/lib/postgresql/data
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data:
